name:                hal
synopsis:            A runtime environment for Haskell applications running on AWS Lambda.
description: |
  This library uniquely supports different types of AWS Lambda Handlers for your
  needs/comfort with advanced Haskell. Instead of exposing a single function
  that constructs a Lambda, this library exposes many.
version:             1.0.0.1
github:              Nike-inc/hal
license:             BSD3
author:              Nike, Inc.
maintainer:          nikeoss
copyright:           2018 Nike, Inc.
category:            Web,AWS
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - OverloadedStrings
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - EmptyCase
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns

library:
  source-dirs: src
  dependencies:
    - aeson
    - base64-bytestring
    - bytestring
    - case-insensitive
    - conduit
    - conduit-extra
    - containers
    - exceptions
    - hashable
    - http-client
    - http-types
    - mtl
    - scientific ^>=0.3.3.0
    - text
    - time
    - unordered-containers

tests:
  hal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hal
    - aeson >=1.2.0.0 && <1.6 || >=2.0.0.0 && <2.2.0.0
    - base64-bytestring
    - bytestring
    - case-insensitive
    - containers
    - hedgehog >= 1.0.3 && < 1.2
    - hspec
    - hspec-hedgehog
    - http-client
    - http-types ^>= 0.12.2
    - raw-strings-qq ^>=1.1
    - scientific
    - text
    - time
    - transformers
    - unordered-containers
    - vector ^>=0.12.0.0
